#module load xl

CC=xlc
CXX=xlC
FC=xlf

CFLAGS=-O2 -qsmp=omp -qoffload 
CXXFLAGS=-O2 -qsmp=omp -qoffload
FFLAGS=-O2 -qsmp=omp -qoffload

LIBS=-Wl,-rpath=$(OLCF_XL_ROOT)/lib  -lm

TARGETS=laplace.xl

all: $(TARGETS) 

%.xl : %.c
	- $(CC) $(CFLAGS)  $(LIBS) $< -o $@

%.xl : %.cpp
	- $(CXX) $(CXXFLAGS)  $(LIBS) $< -o $@

%.xl : %.f90
	- $(FC) $(FFLAGS) $(LIBS) $< -o $@

clean:
	rm -rf $(TARGETS) *.o
