#module use /sw/summit/modulefiles/ums/stf010/Core 
#module load  gcc/11.1.0-latest

CC=gcc
CXX=clang++
FC=gfortran

CFLAGS=-O3 -fopenmp 
CXXFLAGS=-O3 -fopenmp
FFLAGS=-O3 -fopenmp

LIBS=-Wl,-rpath=$(OLCF_GCC_ROOT)/lib64 -foffload="-latomic -lm" -lm 

TARGETS=laplace.gcc

all: $(TARGETS) 

%.gcc : %.c
	- $(CC) $(CFLAGS)  $(LIBS) $< -o $@

%.gcc : %.cpp
	- $(CXX) $(CXXFLAGS)  $(LIBS) $< -o $@

%.gcc : %.f90
	- $(FC) $(FFLAGS) $(LIBS) $< -o $@

clean:
	rm -rf $(TARGETS) *.o
