#module load  gcc/11.1.0
#module load  gcc/10-devel-omp_20201218

COMPILER=gcc

TARGETS=laplace.$(COMPILER)

CC=gcc
CXX=clang++
FC=gfortran

CFLAGS=-O3 -fopenmp 
CXXFLAGS=-O3 -fopenmp
FFLAGS=-O3 -fopenmp

LIBS=-Wl,-rpath=$(GCC_ROOT)/lib64 -foffload="-latomic -lm" -lm 

all : $(TARGETS)

%.gcc : %.c
	- $(CC) $(CFLAGS)  $(LIBS) $< -o $@

%.gcc : %.cpp
	- $(CXX) $(CXXFLAGS)  $(LIBS) $< -o $@

%.gcc : %.f90
	- $(FC) $(FFLAGS) $(LIBS) $< -o $@

clean:
	rm -rf $(TARGETS) *.o
